api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Resources/config/api_resources/']
    collection:
        pagination:
            enabled: true
    formats:
        jsonapi:
            mime_types: ['application/vnd.api+json']